language: node_js
node_js:
  - "0.10"
addons:
  code_climate:
    repo_token: 446459bcd16f200a114ec8bd18f3214555ae084433a19b96417774a4e6eabbdd
after_success:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"